# Generated by Django 5.2.4 on 2025-07-24 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a4d9f2d9-f891-42d9-a3da-8d7a26da8803'), editable=False, primary_key=True, serialize=False),
        ),
    ]
