# Generated by Django 5.2.4 on 2025-07-24 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8f143dc3-96b3-4be7-9de1-01c8abff3368'), editable=False, primary_key=True, serialize=False),
        ),
    ]
