# Generated by Django 5.2.4 on 2025-07-26 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0003_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('558307a6-9cb6-48fe-a71f-df4a547fbac0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
