# Generated by Django 5.2.4 on 2025-08-01 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0004_alter_todo_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField(max_length=40)),
                ('ename', models.CharField()),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('city', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('25f56eb6-6c58-4097-bce0-437012e39d75'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='proxy',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APIapp.emp')),
            ],
            bases=('APIapp.emp',),
        ),
        migrations.CreateModel(
            name='proxy2',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APIapp.emp')),
            ],
            bases=('APIapp.emp',),
        ),
    ]
