# Generated by Django 5.2.4 on 2025-08-01 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0005_emp_students_alter_todo_uid_proxy_proxy2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2028f175-88bd-47d2-9b3f-9e5f871b1744'), editable=False, primary_key=True, serialize=False),
        ),
    ]
