# Generated by Django 5.2.4 on 2025-08-02 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0006_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('15426295-0e04-4dc9-9ba6-9f3f935d6d3e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
